# 1
# a

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
column_names = pd.read_csv('segmentation_names.txt', header=None)
column_names = np.array(column_names)
column_names = column_names.tolist()
column_names = sum(column_names, [])

seg = pd.read_csv('segmentation_data.txt', header=None)
seg.columns = column_names

classes = pd.read_csv('segmentation_classes.txt', delimiter="\t", header= None, index_col=0)

In [3]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler.fit(seg)
seg_norm = min_max_scaler.fit_transform(seg)

# b

In [4]:
from sklearn.cluster import KMeans 
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1)

In [5]:
kmeans.fit(seg_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 421.00279241
start iteration
done sorting
end inner loop
Iteration 1, inertia 392.418231916
start iteration
done sorting
end inner loop
Iteration 2, inertia 387.265002269
start iteration
done sorting
end inner loop
Iteration 3, inertia 384.594740591
start iteration
done sorting
end inner loop
Iteration 4, inertia 382.262053668
start iteration
done sorting
end inner loop
Iteration 5, inertia 380.57209747
start iteration
done sorting
end inner loop
Iteration 6, inertia 378.374108209
start iteration
done sorting
end inner loop
Iteration 7, inertia 375.735497717
start iteration
done sorting
end inner loop
Iteration 8, inertia 374.642484542
start iteration
done sorting
end inner loop
Iteration 9, inertia 374.141115528
start iteration
done sorting
end inner loop
Iteration 10, inertia 373.851154748
start iteration
done sorting
end inner loop
Iteration 11, inertia 373.701171085
start iteration
done sorting

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [6]:
pd.DataFrame(kmeans.cluster_centers_, columns=[seg.columns]) 

REGION-CENTROID-COL  REGION-CENTROID-ROW  REGION-PIXEL-COUNT  \
0             0.253603             0.459865                 0.0   
1             0.302506             0.530862                 0.0   
2             0.513994             0.808937                 0.0   
3             0.535099             0.150167                 0.0   
4             0.251678             0.392749                 0.0   
5             0.748274             0.532041                 0.0   
6             0.769063             0.425930                 0.0   

   SHORT-LINE-DENSITY-5  SHORT-LINE-DENSITY-2  VEDGE-MEAN  VEDGE-SD  \
0              0.026346              0.013746    0.037337  0.002370   
1              0.052260              0.046610    0.100817  0.009420   
2              0.077441              0.005051    0.054474  0.001407   
3              0.027778              0.001667    0.030228  0.000543   
4              0.075622              0.019403    0.077657  0.004149   
5              0.039157              0.037651    0.113530  0.018922   
6              0.014024              0.022654    0.039702  0.002983   

   HEDGE-MEAN  HEDGE-SD  INTENSITY-MEAN  RAWRED-MEAN  RAWBLUE-MEAN  \
0    0.027901  0.002022        0.025942     0.017775      0.042280   
1    0.083972  0.011043        0.400608     0.370347      0.472461   
2    0.046335  0.001401        0.108790     0.091403      0.092414   
3    0.026766  0.000587        0.823246     0.779716      0.894170   
4    0.061240  0.005037        0.147428     0.137485      0.184391   
5    0.107311  0.017627        0.298573     0.277521      0.350081   
6    0.023116  0.002094        0.040385     0.034426      0.057385   

   RAWGREEN-MEAN  EXRED-MEAN  EXBLUE-MEAN  EXGREEN-MEAN  VALUE-MEAN  \
0       0.016464    0.769272     0.216204      0.508343    0.043251   
1       0.353036    0.497146     0.570882      0.213054    0.472461   
2       0.142676    0.679161     0.079002      0.821287    0.134901   
3       0.788761    0.270665     0.666373      0.289386    0.894170   
4       0.117637    0.718250     0.343789      0.354454    0.184648   
5       0.263837    0.593300     0.449242      0.311453    0.350163   
6       0.028059    0.779917     0.222795      0.486886    0.058362   

   SATURATION-MEAN  HUE-MEAN  
0         0.802618  0.180506  
1         0.302263  0.163879  
2         0.414491  0.892333  
3         0.211804  0.125066  
4         0.413414  0.202752  
5         0.303047  0.164359  
6         0.539152  0.244988

In [7]:
pred = kmeans.predict(seg_norm)

In [8]:
from sklearn.metrics import completeness_score, homogeneity_score
classes = np.array(classes)
classes = classes.tolist()
classes = sum(classes, [])
print('Completeness is ', completeness_score(classes,pred))
print('Homogeneity is ', homogeneity_score(classes,pred))

Completeness is  0.611737468433
Homogeneity is  0.610049991469


# c

In [10]:
from sklearn import decomposition
pca = decomposition.PCA(n_components=7)
seg_trans = pca.fit(seg_norm).transform(seg_norm)

In [11]:
np.set_printoptions(precision=2,suppress=True)
print(seg_trans)

[[-0.69  0.53  0.25 ..., -0.08  0.05 -0.05]
 [-0.67  0.51  0.34 ..., -0.04  0.06 -0.04]
 [-0.71  0.77 -0.16 ..., -0.17  0.04 -0.06]
 ..., 
 [-0.51 -0.13 -0.08 ..., -0.03 -0.03 -0.11]
 [-0.48 -0.09 -0.16 ...,  0.   -0.   -0.09]
 [-0.44 -0.11 -0.05 ...,  0.02 -0.21  0.15]]


In [12]:
print(pca.explained_variance_ratio_)

[ 0.61  0.13  0.1   0.05  0.04  0.02  0.02]


# 7 components can explain 97% of the variance

# d

In [13]:
kmeans.fit(seg_trans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 330.871763256
start iteration
done sorting
end inner loop
Iteration 1, inertia 317.06388359
start iteration
done sorting
end inner loop
Iteration 2, inertia 314.229915865
start iteration
done sorting
end inner loop
Iteration 3, inertia 312.363978278
start iteration
done sorting
end inner loop
Iteration 4, inertia 309.953897608
start iteration
done sorting
end inner loop
Iteration 5, inertia 308.968962004
start iteration
done sorting
end inner loop
Iteration 6, inertia 308.726643227
start iteration
done sorting
end inner loop
Iteration 7, inertia 308.537049592
start iteration
done sorting
end inner loop
Iteration 8, inertia 308.292625355
start iteration
done sorting
end inner loop
Iteration 9, inertia 307.73176064
start iteration
done sorting
end inner loop
Iteration 10, inertia 307.340511159
start iteration
done sorting
end inner loop
Iteration 11, inertia 306.756680424
start iteration
done sorting

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [14]:
pred = kmeans.predict(seg_trans)

In [15]:
print('Completeness is ', completeness_score(classes,pred))
print('Homogeneity is ', homogeneity_score(classes,pred))

Completeness is  0.611298362648
Homogeneity is  0.609645388271


# e
# The completeness and homogeneity after implementing PCA are similar with  the two before implementing PCA. However the computation efficiency is improved with PCA.

# 2
# a

In [16]:
def load_jokes(file):
    jokes = np.genfromtxt(file, delimiter=',', dtype=str)
    jokes = np.array(jokes[:,1])
    return jokes

In [17]:
jokes = load_jokes('jokes.csv')

In [18]:
jokes[0]

'A man visits the doctor. The doctor says "I have bad news for you.You have cancer and Alzheimer\'s disease". The man replies "Well thank God I don\'t have cancer!"'

In [19]:
jester = np.genfromtxt('modified_jester_data.csv', delimiter=',')

In [20]:
jester

array([[  3.18,  19.79,   1.34, ...,   0.  ,   0.  ,   0.  ],
       [ 15.08,  10.71,  17.36, ...,  11.34,   6.68,  12.07],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       ..., 
       [ 16.58,  16.63,  15.85, ...,   0.  ,   0.  ,   0.  ],
       [  3.67,   4.45,   3.67, ...,   3.77,   3.77,   3.28],
       [  9.88,  11.73,   9.16, ...,   0.  ,   0.  ,   0.  ]])

# b

In [21]:
from numpy import *
from numpy import linalg as la

In [22]:
def ecludSim(inA,inB):
    return 1.0 / (1.0 + la.norm(inA - inB))

def pearsSim(inA,inB):
    if len(inA) < 3 : return 1.0
    return 0.5 + 0.5 * corrcoef(inA, inB, rowvar = 0)[0][1]

def cosSim(inA,inB):
    num = float(inA.T * inB)
    denom = la.norm(inA)*la.norm(inB)
    return 0.5 + 0.5 * (num / denom)

In [23]:
def standEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0: continue
        overLap = nonzero(logical_and(dataMat[:,item]>0, \
                                      dataMat[:,j]>0))[0]
        if len(overLap) == 0: similarity = 0
        else: similarity = simMeas(dataMat[overLap,item], \
                                   dataMat[overLap,j])
        #print 'the %d and %d similarity is: %f' % (item, j, similarity)
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

In [24]:
def svdEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    data=mat(dataMat)
    U,Sigma,VT = la.svd(data)
    Sig4 = mat(eye(4)*Sigma[:4]) #arrange Sig4 into a diagonal matrix
    xformedItems = data.T * U[:,:4] * Sig4.I  #create transformed items
    for j in range(n):
        userRating = data[user,j]
        if userRating == 0 or j==item: continue
        similarity = simMeas(xformedItems[item,:].T,\
                             xformedItems[j,:].T)
        #print 'the %d and %d similarity is: %f' % (item, j, similarity)
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

In [25]:
def cross_validate_user(dataMat, user, test_ratio, estMethod=standEst, simMeas=pearsSim):
    number_of_items = np.shape(dataMat)[1]
    rated_items_by_user = np.array([i for i in range(number_of_items) if dataMat[user,i]>0])
    test_size = int(test_ratio * len(rated_items_by_user))
    test_indices = np.random.randint(0, len(rated_items_by_user), test_size)
    withheld_items = rated_items_by_user[test_indices]
    original_user_profile = np.copy(dataMat[user])
    dataMat[user, withheld_items] = 0 # So that the withheld test items is not used in the rating estimation below
    error_u = 0.0
    count_u = len(withheld_items)

    # Compute absolute error for user u over all test items
    for item in withheld_items:
        # Estimate rating on the withheld item
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        error_u = error_u + abs(estimatedScore - original_user_profile[item])
    # Now restore ratings of the withheld items to the user profile
    for item in withheld_items:
        dataMat[user, item] = original_user_profile[item]

    # Return sum of absolute errors and the count of test cases for this user
    # Note that these will have to be accumulated for each user to compute MAE
    return error_u, count_u

In [28]:
def test(dataMat, test_ratio, estMethod, name):
    total_error = 0
    total_count = 0
    for u in range(jester.shape[0]):
        error , count = cross_validate_user(dataMat, u, test_ratio, estMethod, simMeas=pearsSim)
        total_error += abs(error)
        total_count += count
    MAE = total_error/total_count
    print('Mean Absoloute Error for ', name,' : ', MAE)

In [29]:
test(jester, 0.2, standEst, 'standard item-based')

Mean Absoloute Error for  standard item-based  :  3.68231981173


In [30]:
test(jester, 0.2, svdEst, 'svd item-based')

Mean Absoloute Error for  svd item-based  :  3.6350199905


# The MAE of standard item-based is slightly higher than the MAE of svd item-based.

#  c

In [132]:
jester

array([[  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       [ 15.08,   0.  ,  17.36, ...,   0.  ,   6.68,  12.07],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       ..., 
       [ 16.58,  16.63,  15.85, ...,   0.  ,   0.  ,   0.  ],
       [  3.67,   4.45,   3.67, ...,   3.77,   3.77,   3.28],
       [  9.88,  11.73,   9.16, ...,   0.  ,   0.  ,   0.  ]])

In [133]:
jester.T

array([[  0.  ,  15.08,   0.  , ...,  16.58,   3.67,   9.88],
       [  0.  ,   0.  ,   0.  , ...,  16.63,   4.45,  11.73],
       [  0.  ,  17.36,   0.  , ...,  15.85,   3.67,   9.16],
       ..., 
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   3.77,   0.  ],
       [  0.  ,   6.68,   0.  , ...,   0.  ,   3.77,   0.  ],
       [  0.  ,  12.07,   0.  , ...,   0.  ,   3.28,   0.  ]])

In [153]:
def print_most_similar_jokes(dataMat, jokes, queryJoke, k, metric=pearsSim):
    simi = []
    for j in [ v for v in range(dataMat.shape[1]) if v != queryJoke ]:
        score = metric(dataMat.T[queryJoke], dataMat.T[j])
        simi.append(score)
    simi = np.array(simi)
    idx = np.argsort(-simi)
    
    print('Selected joke:', '\n')
    print(jokes[queryJoke], '\n')
    print('Top 5 Recommended jokes are :', '\n')
    
    for jk in idx[:5]:
        print(jokes[jk], '\n')

In [156]:
print_most_similar_jokes(jester, jokes, 3, 5,metric=pearsSim)

Selected joke: 

Q. What's the difference between a man and a toilet? A. A toilet doesn't follow you around after you use it. 

Top 5 Recommended jokes are : 

Q: What is the Australian word for a boomerang that won't   come back? A: A stick 

Q. Did you hear about the dyslexic devil worshipper? A. He sold his soul to Santa. 

Q. What's 200 feet long and has 4 teeth? A. The front row at a Willie Nelson Concert. 

An old Scotsmen is sitting with a younger Scottish gentleman and says the boy. "Ah lad look out that window. You see that stone wall there I built it with me own bare hands placed every stone meself.  But do they call me MacGregor the wall builder? No! He Takes a few sips of his beer then says "Aye and look out on that lake and eye that beautiful pier. I built it meself laid every board and hammered each nail but do they call me MacGregor the pier builder? No! He continues..."And lad you see that road? That too I build with me own bare hands. Laid every inch of pavement meself